apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-simple-dev
  namespace: openshift-gitops
spec:
  destination:
    namespace: quarkus-simple-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: config/overlays/dev
    repoURL: https://github.com/rafaeltuelho/quarkus-simple-config.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true